source 'http://rubygems.org'

gem 'rails', '3.1.0'
gem 'haml'
gem 'haml-rails'
gem 'sass-rails'
gem 'jquery-rails'
gem 'coffee-script'
gem 'coffee-filter'
gem 'rack-cache'

gem 'amber-rails', :path => "../.."
